### ISSUE TITLE
Plugin not installed.

### ISSUE THREAD

**Issue by BloodJ** [pitaj/nodebb-plugin-calendar#107]
After install plugin and start server. I saw in log :  
2018-11-26T00:09:13.534Z [30026] - error: /home/nodebb/node_modules/nodebb-plugin-calendar/build/lib/init.js:23
const initCb = (0, _util.callbackify)(async () => {
                                            ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nodebb/nodebb/node_modules/nodebb-plugin-calendar/src/lib/index.js:3:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
2018-11-26T00:09:13.535Z [30026] - warn: [plugins] Unable to parse library for: nodebb-plugin-calendar

I tried to reinstall the plugin but without success.
#node -v
v6.14.4
#npm -v
3.10.10
nodebb-plugin-calendar@1.0.0-alpha.43

**Comment by BloodJ** [comment]
@pitaj thank you very much. That helped.
