### ISSUE TITLE
Add 0.6.x compatibility

### ISSUE THREAD

**Issue by pitaj** [pitaj/nodebb-plugin-calendar#11]
This plugin is affected by the static.init hook change. Fix it.

**Comment by Master-Antonio** [comment]
error: TypeError: Object #<Object> has no method 'get'
    at Object.module.init [as method] (/root/nodebb/node_modules/nodebb-plugin-calendar/library.j                                                                                                                                                                              s:105:9)
    at /root/nodebb/src/plugins.js:460:13
    at /root/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/root/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/root/nodebb/node_modules/async/lib/async.js:124:9)
    at fireStaticHook (/root/nodebb/src/plugins.js:450:9)
    at Object.Plugins.fireHook (/root/nodebb/src/plugins.js:406:5)
    at Plugins.reloadRoutes (/root/nodebb/src/plugins.js:129:11)
    at /root/nodebb/node_modules/async/lib/async.js:656:23
TypeError: Object #<Object> has no method 'get'
    at Object.module.init [as method] (/root/nodebb/node_modules/nodebb-plugin-calendar/library.j                                                                                                                                                                              s:105:9)
    at /root/nodebb/src/plugins.js:460:13
    at /root/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/root/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/root/nodebb/node_modules/async/lib/async.js:124:9)
    at fireStaticHook (/root/nodebb/src/plugins.js:450:9)
    at Object.Plugins.fireHook (/root/nodebb/src/plugins.js:406:5)
    at Plugins.reloadRoutes (/root/nodebb/src/plugins.js:129:11)
    at /root/nodebb/node_modules/async/lib/async.js:656:23

**Comment by TheJason** [comment]
Any update on when this will be resolved?

**Comment by pitaj** [comment]
I'm working on pretty much an entire re-write of the code base right now.
I'm not working about v0.5.x. It's only going to be compatible with v0.6.x.
