### ISSUE TITLE
Error when viewing events

### ISSUE THREAD

**Issue by pitaj** [pitaj/nodebb-plugin-calendar#111]
Stack trace:

```
templates.js:13 

Uncaught TypeError: event.reminders.sort is not a function
    at eventTemplate (templates.js:13)
    at displayEvent (displayEvent.js:5)
    at HTMLAnchorElement.eventClick (index.js:40)
    at Calendar.publiclyTrigger (fullcalendar.js:9352)
    at SubClass.DateComponent.publiclyTrigger (fullcalendar.js:8780)
    at EventPointing.handleClick (fullcalendar.js:6599)
    at HTMLAnchorElement.<anonymous> (fullcalendar.js:3352)
    at HTMLDivElement.dispatch (jquery.js:5183)
    at HTMLDivElement.g.handle (jquery.js:4991)
```

**Comment by jtsimoes** [comment]
Also when I create an event repeating every day like this
![image](https://user-images.githubusercontent.com/34691647/51442410-3c310200-1cd4-11e9-80d6-cfae01f37887.png)
this error is thrown when viewing the /calendar page:
![image](https://user-images.githubusercontent.com/34691647/51442398-13a90800-1cd4-11e9-9993-de0c2b3a7d42.png)

Maybe repetition is broken (?)

**Comment by jtsimoes** [comment]
Reminders appears to be broken too... 😢 
When starting NodeBB I'm getting this error too on console log:

```
2019-01-20T18:50:57.932Z [4567/10548] - error: Cannot read property 'reminders' of null
TypeError: Cannot read property 'reminders' of null
    at reminders (/home/ectua/NodeBB/node_modules/nodebb-plugin-calendar/src/lib/reminders.js:126:40)
    at Array.reduce (<anonymous>)
    at reduce (/home/ectua/NodeBB/node_modules/nodebb-plugin-calendar/src/lib/reminders.js:125:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by pitaj** [comment]
I've done what I can to try to remedy these issues. Try `nodebb-plugin-calendar@1.0.0-alpha.44`. Also, try editing and saving any posts with events in them, that may fix the problems you're seeing.
