### ISSUE TITLE
compatibility issue with 1.15.2

### ISSUE THREAD

**Issue by AliCihan** [pitaj/nodebb-plugin-calendar#135]
With NodeBB 1.15.2 , we are having these error lines in the log:

````
2020-11-25T03:25:53.922Z` [4568/20409] - [33mwarn[39m:    [plugins/nodebb-plugin-calendar] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2020-11-25T03:25:53.923Z [4569/20411] - [33mwarn[39m:    [plugins/nodebb-plugin-calendar] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2020-11-25T03:25:53.925Z [4568/20409] - [33mwarn[39m: [plugins] Unable to load library for: nodebb-plugin-calendar
2020-11-25T03:25:53.926Z [4569/20411] - [33mwarn[39m: [plugins] Unable to load library for: nodebb-plugin-calendar
2020-11-25T03:25:53.926Z [4567/20408] - [33mwarn[39m:    [plugins/nodebb-plugin-calendar] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2020-11-25T03:25:53.926Z [4569/20411] - [31merror[39m: Error: Cannot find module './build/lib'
Require stack:
- /home/fsuzer/nodebb/node_modules/nodebb-plugin-calendar/library.js
- /home/fsuzer/nodebb/src/plugins/index.js
- /home/fsuzer/nodebb/src/meta/configs.js
- /home/fsuzer/nodebb/src/meta/index.js
- /home/fsuzer/nodebb/src/start.js
- /home/fsuzer/nodebb/require-main.js
- /home/fsuzer/nodebb/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/fsuzer/nodebb/node_modules/nodebb-plugin-calendar/library.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
````

**Comment by pitaj** [comment]
I'm unable to reproduce. Can you try reinstalling the plugin?

```sh
npm rm nodebb-plugin-calendar
npm i nodebb-plugin-calendar@latest
```

**Comment by AliCihan** [comment]
> I'm unable to reproduce. Can you try reinstalling the plugin?
> 
> ```shell
> npm rm nodebb-plugin-calendar
> npm i nodebb-plugin-calendar@latest
> ```

Thanks, we solved the issue by reinstalling from npm...
