### ISSUE TITLE
Reminder not working

### ISSUE THREAD

**Issue by zylim97** [pitaj/nodebb-plugin-calendar#153]
Hi calendar reminder is not working and I check the log it said "You do not have enough privileges for this action." , what is the privileges that need for this plugin to send the reminder email?
Version I used:
Nodebb version: 1.19.7
Plugin version: 1.1.3
![image](https://user-images.githubusercontent.com/52324156/174270903-a96cde5e-3a7b-42ac-8246-415c68e4c2f4.png)

**Comment by pitaj** [comment]
I'm not sure. I'll have to try reproducing this myself. Could you please provide the whole error message you see?

**Comment by zylim97** [comment]
2022-06-17T07:23:30.997Z [4567/14189] - [33mwarn[39m: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-calendar

2022-06-17T07:23:30.999Z [4567/14189] - [33mwarn[39m: [plugins/load] DEPRECATION The hook action:post.purge has been deprecated as of v1.19.6, and slated for removal in v2.1.0. Please use action:posts.purge instead. The following plugins are still listening for this hook:
  * nodebb-plugin-dbsearch
  * nodebb-plugin-mentions
  * nodebb-plugin-calendar
2022-06-17T07:23:31.147Z [4567/14189] - [32minfo[39m: [api] Adding 0 route(s) to `api/v3/plugins`
2022-06-17T07:23:31.174Z [4567/14189] - [32minfo[39m: [router] Routes added
2022-06-17T07:23:31.182Z [4567/14189] - [32minfo[39m: NodeBB Ready
2022-06-17T07:23:31.184Z [4567/14189] - [32minfo[39m: Enabling 'trust proxy'
2022-06-17T07:23:31.186Z [4567/14189] - [32minfo[39m: NodeBB is now listening on: 0.0.0.0:4567
2022-06-17T07:27:31.217Z [4567/14189] - [31merror[39m: You do not have enough privileges for this action.
2022-06-17T07:29:31.231Z [4567/14189] - [31merror[39m: You do not have enough privileges for this action.
2022-06-17T07:47:31.322Z [4567/14189] - [31merror[39m: You do not have enough privileges for this action.
2022-06-17T07:49:31.333Z [4567/14189] - [31merror[39m: You do not have enough privileges for this action.
2022-06-17T09:02:31.610Z [4567/14189] - [31merror[39m: You do not have enough privileges for this action.
2022-06-17T09:04:31.619Z [4567/14189] - [31merror[39m: You do not have enough privileges for this action.
2022-06-17T09:26:46.606Z [4567/14189] - [31merror[39m: plugins.calendar.getResponses
Error: revalidate-failure
    at validateSession (/home/ubuntu/nodebb/src/socket.io/index.js:216:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at onMessage (/home/ubuntu/nodebb/src/socket.io/index.js:153:3)
  started
