### ISSUE TITLE
Calendar Plugin will not show up in nodeBB ACP 0.8.2

### ISSUE THREAD

**Issue by cloudzombie** [pitaj/nodebb-plugin-calendar#27]
#27 
I installed from your directions, deleting the folder, and installing from git clone, and updating via: npm. 

I cannot get the calendar to show up in the front or backend at all, I am getting this in my log. 

28/9 06:25 [17390] - info: NodeBB Ready
28/9 06:25 [17390] - info: NodeBB is now listening on: 0.0.0.0:4567
[cluster] Reloading...
28/9 06:26 [17390] - error: Error: Cannot find module './postTools'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at /home/cloud/mynodebb/node_modules/nodebb-plugin-calendar/subs/posts.js:5:38
    at Object.<anonymous> (/home/cloud/mynodebb/node_modules/nodebb-plugin-calendar/subs/posts.js:78:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
28/9 06:26 [17390] - warn: [plugins] Unable to parse library for: nodebb-plugin-calendar

28/9 06:26 [17390] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-calendar

**Comment by pitaj** [comment]
This plugin is not in a stable condition. I've been on a hiatus from is development for a while. It doesn't work at all right now.
