### ISSUE TITLE
Unable to parse library for: nodebb-plugin-calendar

### ISSUE THREAD

**Issue by spicewiesel** [pitaj/nodebb-plugin-calendar#56]
after activating the plugin I see the following during the nodebb restart:

```
21/8 12:27 [2271] - info: [database] Checking database indices.

/home/spicewiesel/bin/nodebb/node_modules/nodebb-plugin-calendar/build/lib/index.js:26
const addNavigation = (navs, callback) => {
^^^^^
21/8 12:27 [2271] - error: SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/spicewiesel/bin/nodebb/node_modules/nodebb-plugin-calendar/library.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Plugins.requireLibrary (/home/spicewiesel/bin/nodebb/src/plugins.js:42:33)
    at registerHooks (/home/spicewiesel/bin/nodebb/src/plugins/load.js:88:13)
    at /home/spicewiesel/bin/nodebb/src/plugins/load.js:31:6
    at /home/spicewiesel/bin/nodebb/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/spicewiesel/bin/nodebb/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/spicewiesel/bin/nodebb/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/spicewiesel/bin/nodebb/node_modules/async/lib/async.js:731:9)
    at /home/spicewiesel/bin/nodebb/src/plugins/load.js:29:10
    at /home/spicewiesel/bin/nodebb/src/plugins/load.js:317:5
21/8 12:27 [2271] - warn: [plugins] Unable to parse library for: nodebb-plugin-calendar
```

I am running nodebb v.1.1.3 and had the same issue with v.1.1.2

thanks!

**Comment by pitaj** [comment]
This plugin requires node v4 or newer. Try upgrading node.js with the utility **n** or **npm**
